---
title: "Project 08: Hidden Markov Model"
author: "Little Butler"
date: "`r format(Sys.time(), '%Y%m%d')`"
output:
  github_document:
    html_preview: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
library('reticulate')
reticulate::use_condaenv(condaenv = "r-reticulate")
```

## Viterbi ( Hidden Markov Model)

The basis of this project is on Hidden Markov models and Markov chains. Based on observation data we try to gather predictions on hidden states.
An applicable example of this in biology is DNA sequences and CpG islands aas the hidden states. CpG islands are groups of methylated (silences, the genes won't be expressed) pieces of DNA compared to non-methylated.
Going from initial state (observed) to second state or transition state and the product of probalities calculated between from state to state is the basis of this assignment.

```{python}
# Example observation sequence
obs = "GGCACTGAA"

# Example initial probabilities (probability of starting in each state)
init_probs = {
    "I": 0.2,
    "G": 0.8
}

# Example transition probabilities (probability of moving from one state to another)
trans_probs = {
    "I": {"I": 0.7, "G": 0.3},
    "G": {"I": 0.1, "G": 0.9}
}

# Example emission probabilities (probability of observing a symbol in a given state)
emit_probs = {
    "I": {"A": 0.1, "C": 0.4, "G": 0.4, "T": 0.1},
    "G": {"A": 0.3, "C": 0.2, "G": 0.2, "T": 0.3}
}


import math
import numpy as np


def viterbi(obs, init_probs, trans_probs, emit_probs):
  # the args in this function takes the state probs from above

    # get the unique hidden states from keys to a list
    hidden_states = list(init_probs.keys())
    # print(hidden_states[1])
    

    state_step_probs = []
    max_prev_hidden_states = []

    # first probs. Initialization
    state_step_probs.append({})  # store an empty dict inside the empty list
    max_prev_hidden_states.append("Start")
    for h_state in hidden_states:  # iterate through the hidden states list of keys

        first_obs = obs[0]  # access the dict which is the first element
        state_prob = init_probs[h_state] * emit_probs[h_state][first_obs]
        state_step_probs[0][h_state] = state_prob
        
        # print(emit_probs)
        # print(state_step_probs)
    
    # iterate through the observations starting at 1 until the end
    for i, step_observation in enumerate(obs[1:], 1):
      
    # for i, step_observation in range(len(obs[1:]))  
        
        state_step_probs.append({})
        max_prev_hidden_states.append({})

        for current_state in hidden_states:

            possible_prev_state_paths = []

            for prev_state in hidden_states:
                state_prob = (state_step_probs[i-1][prev_state] * trans_probs[prev_state][current_state] * 
                              emit_probs[current_state][step_observation])
                possible_prev_state_paths.append(state_prob)
            
            max_prob_idx = int(np.argmax(possible_prev_state_paths))
            max_prob = possible_prev_state_paths[max_prob_idx]
            state_step_probs[i][current_state] = max_prob

            max_previous_state = hidden_states[max_prob_idx]
            max_prev_hidden_states[i][current_state] = max_previous_state
        
    best_hidden_sequence = ""
    max_state = sorted(state_step_probs[-1].items(), key=lambda x: x[1])[-1][0]
    best_hidden_sequence = max_state+best_hidden_sequence

    for i in range(len(state_step_probs)-1, 0, -1):
        max_state = max_prev_hidden_states[i][max_state]
        best_hidden_sequence = max_state+best_hidden_sequence
    
    return best_hidden_sequence


``
